-- Exécuter avec ACCOUNTADMIN pour créer l'environnement du pipeline.
-- Remplacer AIRFLOW_SVC si un autre nom d'utilisateur de service est choisi.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;

GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.STAGING TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.MARTS TO ROLE TRANSFORMER;

CREATE USER IF NOT EXISTS AIRFLOW_SVC
    DEFAULT_ROLE = TRANSFORMER
    DEFAULT_WAREHOUSE = NYC_TAXI_WH
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE TRANSFORMER TO USER AIRFLOW_SVC;

-- À exécuter après avoir généré une clé publique RSA pour AIRFLOW_SVC :
-- ALTER USER AIRFLOW_SVC SET RSA_PUBLIC_KEY = '<CLE_PUBLIQUE_RSA_SANS_EN-TETE_NI_SAUTS_DE_LIGNE>';